module.exports = {
  GREETINGS: [/^(hello|hi|greetings)(\.|\!)?$/i],
  RANDOM_FACTS: [
    'The estimated year that the last Bitcoin will be mined is 2140, based on the Bitcoin block having a dividing frequency of four years.',
    'Apart from mining, trading and holding Bitcoin, many people today are making a fortune selling Bitcoin graphics cards and mining hardware, being likened to the profit made from the sales of shovels during the California Gold Rush of the 1880s.',
    'Here is a shocker: Bitcoin is not the first cryptocurrency. In fact, the award goes to Digicash, which was founded years before Bitcoin came into existence. It was created by David Chaum in 1989 and is also based on cryptographic protocols, but it wasn’t popular.',
    'According to the Bitcoin white paper, it is claimed to have been created by a mysterious person, or a group of people, referred to as Satoshi Nakamoto. The name, however, is a pseudonym to keep the actual person behind it off the grid. Although, it has been used by the unknown person, or people, in its white paper, and also used in the creation and deployment of its original referenced implementation.',
    'The creator(s) of Bitcoin owns around 21 1 million of the total that will ever be in existence.',
    'The date Hanyecz made his purchase , May 22nd, is now termed, “Bitcoin Pizza Day” and is celebrated by cryptocurrency enthusiasts worldwide.',
    'A few years ago, the FBI shut down the Silk Road which was a big black market website where Bitcoin was frequently used to make different purchases. FBI acquired all the Bitcoins that were circulating around the website, which is around 1.5% of all the world’s Bitcoin. ',
    'More conventional forms of payment, such as bank transfer, can be tracked and, if needed, reversed. This isn\'t the case with Bitcoin. Once the money has been sent, you can\'t recoup it. It\'s vital, therefore, that you double-check the address you\'re sending the funds to.',
    ' It is interesting to note that Bitcoin miners have surpassed 80% of the total number of bitcoins that will be in existence.',
    'In 2016, the cryptocurrency became the first to make it out of the Earth\'s atmosphere and into space. Cloud provider Genesis Mining tied a Bitcoin paper wallet and a 3D model of Bitcoin to a weather balloon, using a GoPro to track its progress. Successful transactions were carried out at 20 and 34 kilometres altitude.',
    'Just as dollars can be divided into cents and pounds into pence, Bitcoins also have their own denominations, but they\'re much smaller. Named after the mysterious inventor of the cryptocurrency, 1 Satoshi byte is worth 0.00000001 Bitcoin, a tiny amount!',
    'First Bitcoin transaction was a purchase of two … pizzas. Two pizzas were bought for 10 000 BTC. Yes, 10 000 BTC. It was in 2010, when such amount of BTC was worth 25 USD.',
    '',
    '',
    '',
  ],
};
